name: store_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.7.0
  modal_progress_hud_nsn: ^0.5.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  go_router: ^14.2.8
  get_it: ^8.0.0
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf